# -*- coding: utf-8 -*-
"""swarmintelligence3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TlD1Byt1LF7iJPA9il9XPj16jofCmAv1
"""

import random
#random seed
random.seed(78)
def f(x):
   return (x-7)**2+4

positions = [random.uniform(0,14) for i in range(10)]
velocities = [0 for i in range(len(positions))] # Initialize velocities with the same length as positions
pbest_pos = positions[:]
gbest = min(pbest_pos, key=f)
w, c1, c2 = 0.65 , 1.5, 1.5
iterations = 40

for it in range(iterations):
    for i in range(len(positions)): # Iterate over all particles, which is 10
        r1, r2 = random.random(), random.random()
        # Calculate new velocity
        velocities[i] = w * velocities[i] + c1 * r1 * (pbest_pos[i] - positions[i]) + c2 * r2 * (gbest - positions[i])
        # Update particle position
        positions[i] = positions[i] + velocities[i]
        # Update personal best position if current position is better
        if f(positions[i]) < f(pbest_pos[i]):
            pbest_pos[i] = positions[i]
    # Update global best after all particles have moved and updated their personal bests
    gbest = min(pbest_pos, key=f)

print("Swarm converged near x =", gbest)



