# -*- coding: utf-8 -*-
"""swarm_intelligencelab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11o4GcAuEemapvY2JDRvuzRx5EepTUVwr
"""

import random

# Assign a unique roll number for personalized and reproducible results.
roll_number = 78

# Seed the random number generator to ensure reproducibility of results.
random.seed(roll_number)

# Calculate the expected minimum position based on the roll number for personalization.
expected_min_position = roll_number // 10

# Define the expected minimum value of the function.
expected_min_value = 4

# Define the objective function, a parabola with its minimum at a specific position and value.
def objective(x):
    return (x - expected_min_position) ** 2 + expected_min_value

# Define the gradient (derivative) of the objective function, indicating the direction of steepest ascent.
def gradient(x):
    return 2 * (x - expected_min_position)

# Initialize x with a random starting value within a specified range.
x = random.uniform(-10, 10)

# Set the learning rate, which controls the step size in each iteration of gradient descent.
learning_rate = 0.1

# Define the number of iterations for the gradient descent process.
iterations = 200

# Perform gradient descent to find the minimum of the objective function.
for _ in range(iterations):
    x = x - learning_rate * gradient(x)

# The final value of x represents the best position found for the minimum.
best_position = x

# Calculate the function's value at the best position found.
minimum_value = objective(x)

print("Roll Number:", roll_number)
print("Best Position:", best_position)
print("Minimum Function Value:", minimum_value)
print("Expected Minimum Position:", expected_min_position)
print("Expected Minimum Value:", expected_min_value)

